import { createClient } from '@/lib/supabase/server';
import { TasksPageClient } from '@/components/admin/tasks/TasksPageClient';
import type { AdminTask, TaskStatus, TaskPriority, TaskCategory } from '@/types/dashboard';

export const dynamic = 'force-dynamic';

export const metadata = {
  title: 'Tasks — Samvaya Admin',
};

function rowToTask(row: any): AdminTask {
  return {
    id: row.id,
    taskType: row.task_type,
    title: row.title,
    entityType: row.entity_type,
    entityId: row.entity_id,
    status: (row.status ?? 'open') as TaskStatus,
    priority: (row.priority ?? 'normal') as TaskPriority,
    taskCategory: (row.task_category ?? 'manual') as TaskCategory,
    dueDate: row.due_date,
    notes: row.notes,
    actionHref: row.action_href,
    applicantName: row.applicant_name ?? null,
    applicantPhone: row.applicant_phone ?? null,
    applicantEmail: row.applicant_email ?? null,
    createdAt: row.created_at,
    resolvedAt: row.resolved_at,
    isAutoGenerated: row.is_auto_generated,
  };
}

export default async function TasksPage() {
  const supabase = await createClient();

  // Fetch all non-closed tasks + last 7 days of closed tasks
  const sevenDaysAgo = new Date();
  sevenDaysAgo.setDate(sevenDaysAgo.getDate() - 7);

  const { data: rows } = await supabase
    .from('admin_tasks' as never)
    .select('*')
    .order('created_at', { ascending: false }) as any;

  const tasks: AdminTask[] = (rows ?? [])
    .filter((row: any) => {
      if (row.status !== 'closed') return true;
      const resolved = row.resolved_at ? new Date(row.resolved_at) : null;
      return resolved && resolved > sevenDaysAgo;
    })
    .map(rowToTask);

  return (
    <div>
      <TasksPageClient initialTasks={tasks} />
    </div>
  );
}
