import { createClient } from '@/lib/supabase/server';
import { logActivity } from '@/lib/admin/activity';
import type { AdminTask, TaskStatus, TaskPriority, TaskCategory } from '@/types/dashboard';

function rowToTask(row: any): AdminTask {
  return {
    id: row.id,
    taskType: row.task_type,
    title: row.title,
    entityType: row.entity_type,
    entityId: row.entity_id,
    status: row.status as TaskStatus,
    priority: (row.priority ?? 'normal') as TaskPriority,
    taskCategory: (row.task_category ?? 'manual') as TaskCategory,
    dueDate: row.due_date,
    notes: row.notes,
    actionHref: row.action_href,
    applicantName: row.applicant_name ?? null,
    applicantPhone: row.applicant_phone ?? null,
    applicantEmail: row.applicant_email ?? null,
    createdAt: row.created_at,
    resolvedAt: row.resolved_at,
    isAutoGenerated: row.is_auto_generated,
  };
}

export async function GET(request: Request) {
  try {
    const supabase = await createClient();

    const {
      data: { user },
    } = await supabase.auth.getUser();
    if (!user) {
      return new Response(JSON.stringify({ error: 'Unauthorized' }), { status: 401 });
    }

    const { data: userData } = await supabase
      .from('users')
      .select('role')
      .eq('id', user.id)
      .single();

    if (!userData || (userData.role !== 'admin' && userData.role !== 'super_admin')) {
      return new Response(JSON.stringify({ error: 'Forbidden' }), { status: 403 });
    }

    const url = new URL(request.url);
    const status = url.searchParams.get('status');
    const taskType = url.searchParams.get('task_type');
    const priority = url.searchParams.get('priority');
    const taskCategory = url.searchParams.get('task_category');
    const showClosed = url.searchParams.get('show_closed') === 'true';
    const page = parseInt(url.searchParams.get('page') || '1');
    const perPage = parseInt(url.searchParams.get('per_page') || '100');
    const offset = (page - 1) * perPage;

    const queryResult = await supabase
      .from('admin_tasks' as never)
      .select('*', { count: 'exact' })
      .order('created_at', { ascending: false });

    let { data: allData, count, error } = queryResult as any;

    if (!error && allData) {
      if (status) {
        allData = allData.filter((t: any) => t.status === status);
      } else if (!showClosed) {
        // By default hide closed tasks (unless explicitly requested)
        allData = allData.filter((t: any) => t.status !== 'closed');
      }
      if (taskType) {
        allData = allData.filter((t: any) => t.task_type === taskType);
      }
      if (priority) {
        allData = allData.filter((t: any) => t.priority === priority);
      }
      if (taskCategory) {
        allData = allData.filter((t: any) => t.task_category === taskCategory);
      }
      allData = allData.slice(offset, offset + perPage);
    }

    if (error) {
      return new Response(JSON.stringify({ error: error.message }), { status: 500 });
    }

    const tasks: AdminTask[] = (allData || []).map(rowToTask);

    return new Response(JSON.stringify({ tasks, total: count || 0 }), { status: 200 });
  } catch (err) {
    console.error('[GET /api/admin/tasks]', err);
    return new Response(JSON.stringify({ error: 'Internal server error' }), { status: 500 });
  }
}

export async function POST(request: Request) {
  try {
    const supabase = await createClient();

    const {
      data: { user },
    } = await supabase.auth.getUser();
    if (!user) {
      return new Response(JSON.stringify({ error: 'Unauthorized' }), { status: 401 });
    }

    const { data: userData } = await supabase
      .from('users')
      .select('role')
      .eq('id', user.id)
      .single();

    if (!userData || (userData.role !== 'admin' && userData.role !== 'super_admin')) {
      return new Response(JSON.stringify({ error: 'Forbidden' }), { status: 403 });
    }

    const body = await request.json();
    const {
      title,
      task_type = 'manual',
      task_category = 'manual',
      priority = 'normal',
      due_date,
      notes,
      action_href,
      entity_type,
      entity_id,
      applicant_name,
      applicant_phone,
      applicant_email,
    } = body;

    if (!title) {
      return new Response(JSON.stringify({ error: 'Title is required' }), { status: 400 });
    }

    const result = await supabase
      .from('admin_tasks' as never)
      .insert({
        task_type,
        task_category,
        priority,
        title,
        entity_type: entity_type ?? null,
        entity_id: entity_id ?? null,
        status: 'open',
        due_date: due_date ?? null,
        notes: notes ?? null,
        action_href: action_href ?? null,
        applicant_name: applicant_name ?? null,
        applicant_phone: applicant_phone ?? null,
        applicant_email: applicant_email ?? null,
        created_by: user.id,
        is_auto_generated: false,
      } as never)
      .select()
      .single();

    const { data, error } = result as any;

    if (error) {
      return new Response(JSON.stringify({ error: error.message }), { status: 500 });
    }

    await logActivity(user.id, 'created_admin_task', 'admin_task', data.id, {
      title,
      taskType: task_type,
    });

    return new Response(JSON.stringify({ task: rowToTask(data) }), { status: 201 });
  } catch (err) {
    console.error('[POST /api/admin/tasks]', err);
    return new Response(JSON.stringify({ error: 'Internal server error' }), { status: 500 });
  }
}
