import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import { requireAdmin } from '@/lib/admin/auth';
import { logActivity } from '@/lib/admin/activity';
import type { AdminTask, TaskStatus, TaskPriority, TaskCategory } from '@/types/dashboard';

function rowToTask(row: any): AdminTask {
  return {
    id: row.id,
    taskType: row.task_type,
    title: row.title,
    entityType: row.entity_type,
    entityId: row.entity_id,
    status: row.status as TaskStatus,
    priority: (row.priority ?? 'normal') as TaskPriority,
    taskCategory: (row.task_category ?? 'manual') as TaskCategory,
    dueDate: row.due_date,
    notes: row.notes,
    actionHref: row.action_href,
    applicantName: row.applicant_name ?? null,
    applicantPhone: row.applicant_phone ?? null,
    applicantEmail: row.applicant_email ?? null,
    createdAt: row.created_at,
    resolvedAt: row.resolved_at,
    isAutoGenerated: row.is_auto_generated,
  };
}

export async function GET(request: NextRequest) {
  try {
    const authResult = await requireAdmin();
    if (authResult.error) return authResult.error;

    const supabase = await createClient();

    const url = new URL(request.url);
    const status = url.searchParams.get('status');
    const taskType = url.searchParams.get('task_type');
    const priority = url.searchParams.get('priority');
    const taskCategory = url.searchParams.get('task_category');
    const showClosed = url.searchParams.get('show_closed') === 'true';
    const page = parseInt(url.searchParams.get('page') || '1');
    const perPage = parseInt(url.searchParams.get('per_page') || '100');
    const offset = (page - 1) * perPage;

    let query = (supabase as any)
      .from('admin_tasks')
      .select('*', { count: 'exact' })
      .order('created_at', { ascending: false });

    if (status) {
      query = query.eq('status', status);
    } else if (!showClosed) {
      query = query.neq('status', 'closed');
    }
    if (taskType) query = query.eq('task_type', taskType);
    if (priority) query = query.eq('priority', priority);
    if (taskCategory) query = query.eq('task_category', taskCategory);
    query = query.range(offset, offset + perPage - 1);

    const { data, count, error } = await query;

    if (error) {
      console.error('[GET /api/admin/tasks] db error:', error.message);
      return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
    }

    const tasks: AdminTask[] = (data || []).map(rowToTask);
    return NextResponse.json({ tasks, total: count || 0 });
  } catch (err) {
    console.error('[GET /api/admin/tasks]', err);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

export async function POST(request: NextRequest) {
  try {
    const authResult = await requireAdmin();
    if (authResult.error) return authResult.error;
    const { admin } = authResult;

    const supabase = await createClient();

    const body = await request.json();
    const {
      title,
      task_type = 'manual',
      task_category = 'manual',
      priority = 'normal',
      due_date,
      notes,
      action_href,
      entity_type,
      entity_id,
      applicant_name,
      applicant_phone,
      applicant_email,
    } = body;

    if (!title) {
      return NextResponse.json({ error: 'Title is required' }, { status: 400 });
    }

    const { data, error } = await (supabase as any)
      .from('admin_tasks')
      .insert({
        task_type,
        task_category,
        priority,
        title,
        entity_type: entity_type ?? null,
        entity_id: entity_id ?? null,
        status: 'open',
        due_date: due_date ?? null,
        notes: notes ?? null,
        action_href: action_href ?? null,
        applicant_name: applicant_name ?? null,
        applicant_phone: applicant_phone ?? null,
        applicant_email: applicant_email ?? null,
        created_by: admin.id,
        is_auto_generated: false,
      })
      .select()
      .single();

    if (error) {
      console.error('[POST /api/admin/tasks] db error:', error.message);
      return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
    }

    await logActivity(admin.id, 'created_admin_task', 'admin_task', data.id, {
      title,
      taskType: task_type,
    });

    return NextResponse.json({ task: rowToTask(data) }, { status: 201 });
  } catch (err) {
    console.error('[POST /api/admin/tasks]', err);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
