import { createClient } from '@/lib/supabase/server';
import { logActivity } from '@/lib/admin/activity';
import type { AdminTask } from '@/types/dashboard';

export async function GET(request: Request) {
  try {
    const supabase = await createClient();

    // Auth check
    const {
      data: { user },
    } = await supabase.auth.getUser();
    if (!user) {
      return new Response(JSON.stringify({ error: 'Unauthorized' }), { status: 401 });
    }

    const { data: userData } = await supabase
      .from('users')
      .select('role')
      .eq('id', user.id)
      .single();

    if (!userData || (userData.role !== 'admin' && userData.role !== 'super_admin')) {
      return new Response(JSON.stringify({ error: 'Forbidden' }), { status: 403 });
    }

    // Parse query params
    const url = new URL(request.url);
    const status = url.searchParams.get('status');
    const taskType = url.searchParams.get('task_type');
    const page = parseInt(url.searchParams.get('page') || '1');
    const perPage = parseInt(url.searchParams.get('per_page') || '50');
    const offset = (page - 1) * perPage;

    // Build query - note: filtering done client-side after fetch to avoid type issues
    const queryResult = await supabase
      .from('admin_tasks' as never)
      .select('*', { count: 'exact' })
      .order('created_at', { ascending: false });

    let { data: allData, count, error } = queryResult as any;

    if (!error && allData) {
      // Apply filters
      if (status) {
        allData = allData.filter((t: any) => t.status === status);
      }
      if (taskType) {
        allData = allData.filter((t: any) => t.task_type === taskType);
      }
      // Apply pagination
      allData = allData.slice(offset, offset + perPage);
    }

    const data = allData;

    if (error) {
      return new Response(JSON.stringify({ error: error.message }), { status: 500 });
    }

    // Convert snake_case to camelCase
    const tasks: AdminTask[] = (data || []).map((row: any) => ({
      id: row.id,
      taskType: row.task_type,
      title: row.title,
      entityType: row.entity_type,
      entityId: row.entity_id,
      status: row.status,
      dueDate: row.due_date,
      notes: row.notes,
      actionHref: row.action_href,
      createdAt: row.created_at,
      resolvedAt: row.resolved_at,
      isAutoGenerated: row.is_auto_generated,
    }));

    return new Response(JSON.stringify({ tasks, total: count || 0 }), { status: 200 });
  } catch (err) {
    console.error('[GET /api/admin/tasks]', err);
    return new Response(JSON.stringify({ error: 'Internal server error' }), { status: 500 });
  }
}

export async function POST(request: Request) {
  try {
    const supabase = await createClient();

    // Auth check
    const {
      data: { user },
    } = await supabase.auth.getUser();
    if (!user) {
      return new Response(JSON.stringify({ error: 'Unauthorized' }), { status: 401 });
    }

    const { data: userData } = await supabase
      .from('users')
      .select('role')
      .eq('id', user.id)
      .single();

    if (!userData || (userData.role !== 'admin' && userData.role !== 'super_admin')) {
      return new Response(JSON.stringify({ error: 'Forbidden' }), { status: 403 });
    }

    const body = await request.json();
    const { title, task_type = 'manual', due_date, notes, action_href } = body;

    if (!title) {
      return new Response(JSON.stringify({ error: 'Title is required' }), { status: 400 });
    }

    // Insert task
    const result = await supabase
      .from('admin_tasks' as never)
      .insert({
        task_type,
        title,
        entity_type: null,
        entity_id: null,
        status: 'needs_action',
        due_date,
        notes,
        action_href,
        created_by: user.id,
        is_auto_generated: false,
      } as never)
      .select()
      .single();

    const { data, error } = result as any;

    if (error) {
      return new Response(JSON.stringify({ error: error.message }), { status: 500 });
    }

    // Log activity
    await logActivity(user.id, 'created_admin_task', 'admin_task', data.id, {
      title,
      taskType: task_type,
    });

    // Convert to camelCase
    const task: AdminTask = {
      id: data.id,
      taskType: data.task_type,
      title: data.title,
      entityType: data.entity_type,
      entityId: data.entity_id,
      status: data.status,
      dueDate: data.due_date,
      notes: data.notes,
      actionHref: data.action_href,
      createdAt: data.created_at,
      resolvedAt: data.resolved_at,
      isAutoGenerated: data.is_auto_generated,
    };

    return new Response(JSON.stringify({ task }), { status: 201 });
  } catch (err) {
    console.error('[POST /api/admin/tasks]', err);
    return new Response(JSON.stringify({ error: 'Internal server error' }), { status: 500 });
  }
}
