// Dashboard-specific types for the admin command center

export type AlertType = 'payment' | 'bgv' | 'match' | 'stalled' | 'verification';

export interface DashboardAlert {
  id: string;
  userId: string;
  name: string;
  message: string;
  priority: 'high' | 'medium' | 'low';
  alertType: AlertType;
  actionLabel: string;
  actionHref?: string;
  actionEndpoint?: string;
  actionPayload?: Record<string, unknown>;
  daysStuck?: number;

  // Profile context
  age?: number;
  gender?: string;
  specialty?: string;
  city?: string;
  photoUrl?: string;

  // Secondary action
  secondaryActionLabel?: string;
  secondaryActionHref?: string;

  // Match-specific
  hoursRemaining?: number;
  waitingOn?: string;
  compatibilityScore?: number;

  // Email nudge support (two-step inline send)
  nudgeEmailTo?: string;
  nudgeEmailSubject?: string;
  nudgeEmailBody?: string;
}

export interface DashboardMatch {
  suggestionId: string;
  presentationId: string | null;
  personA: { id: string; name: string; details?: string; primaryPhotoUrl?: string; gender?: string };
  personB: { id: string; name: string; details?: string; primaryPhotoUrl?: string; gender?: string };
  compatibilityScore: number;
  matchReason: string;
  fullNarrative: string;
  compatibilityReport: Record<string, unknown> | null;
  currentStage: 'pending_review' | 'approved' | 'presented' | 'mutual_interest';
  daysInStage: number;
  nextAction: string;
  adminNotes: string | null;
}

export interface DashboardActivityLog {
  id: string;
  actorName: string;
  action: string;
  entityType: string;
  entityId: string;
  createdAt: string;
}

export interface DashboardCommLog {
  id: string;
  recipientName: string;
  subject: string;
  sentAt: string;
  status: 'sent' | 'failed' | 'pending';
  channel: string;
}

export interface DistributionEntry {
  label: string;
  count: number;
}

export interface MatchStageCounts {
  pendingReview: number;
  approvedReady: number;
  presentedPending: number;
  mutualInterest: number;
}

export interface PipelineStripStage {
  stage: string;
  key: string;
  count: number;
  conversionPct: number | null;
  trend?: { direction: 'up' | 'down' | 'flat'; percentage: number };
  href: string;
}

export interface AdminTask {
  id: string;
  taskType: string;
  title: string;
  entityType: string | null;
  entityId: string | null;
  status: 'needs_action' | 'in_progress' | 'done';
  dueDate: string | null;
  notes: string | null;
  actionHref: string | null;
  createdAt: string;
  resolvedAt: string | null;
  isAutoGenerated: boolean;
}
