import { createClient } from '@/lib/supabase/server';
import { logActivity } from '@/lib/admin/activity';
import type { AdminTask } from '@/types/dashboard';

export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  try {
    const supabase = await createClient();

    // Auth check
    const {
      data: { user },
    } = await supabase.auth.getUser();
    if (!user) {
      return new Response(JSON.stringify({ error: 'Unauthorized' }), { status: 401 });
    }

    const { data: userData } = await supabase
      .from('users')
      .select('role')
      .eq('id', user.id)
      .single();

    if (!userData || (userData.role !== 'admin' && userData.role !== 'super_admin')) {
      return new Response(JSON.stringify({ error: 'Forbidden' }), { status: 403 });
    }

    const body = await request.json();
    const { status, notes, due_date } = body;

    // Build update object
    const updateData: Record<string, unknown> = {};
    if (status !== undefined) {
      updateData.status = status;
      if (status === 'done') {
        updateData.resolved_at = new Date().toISOString();
      }
    }
    if (notes !== undefined) {
      updateData.notes = notes;
    }
    if (due_date !== undefined) {
      updateData.due_date = due_date;
    }

    // Update task
    const result = await supabase
      .from('admin_tasks' as never)
      .update(updateData as never)
      .eq('id', id)
      .select()
      .single();

    const { data, error } = result as any;

    if (error) {
      return new Response(JSON.stringify({ error: error.message }), { status: 500 });
    }

    if (!data) {
      return new Response(JSON.stringify({ error: 'Task not found' }), { status: 404 });
    }

    // Log activity
    if (status) {
      await logActivity(user.id, `updated_admin_task_status_to_${status}`, 'admin_task', data.id, {
        taskId: data.id,
        newStatus: status,
      });
    }

    // Convert to camelCase
    const task: AdminTask = {
      id: data.id,
      taskType: data.task_type,
      title: data.title,
      entityType: data.entity_type,
      entityId: data.entity_id,
      status: data.status,
      dueDate: data.due_date,
      notes: data.notes,
      actionHref: data.action_href,
      createdAt: data.created_at,
      resolvedAt: data.resolved_at,
      isAutoGenerated: data.is_auto_generated,
    };

    return new Response(JSON.stringify({ task }), { status: 200 });
  } catch (err) {
    console.error('[PATCH /api/admin/tasks/[id]]', err);
    return new Response(JSON.stringify({ error: 'Internal server error' }), { status: 500 });
  }
}
