import { createClient } from '@/lib/supabase/server';
import { logActivity } from '@/lib/admin/activity';
import type { AdminTask, TaskStatus, TaskPriority, TaskCategory } from '@/types/dashboard';

function rowToTask(row: any): AdminTask {
  return {
    id: row.id,
    taskType: row.task_type,
    title: row.title,
    entityType: row.entity_type,
    entityId: row.entity_id,
    status: row.status as TaskStatus,
    priority: (row.priority ?? 'normal') as TaskPriority,
    taskCategory: (row.task_category ?? 'manual') as TaskCategory,
    dueDate: row.due_date,
    notes: row.notes,
    actionHref: row.action_href,
    applicantName: row.applicant_name ?? null,
    applicantPhone: row.applicant_phone ?? null,
    applicantEmail: row.applicant_email ?? null,
    createdAt: row.created_at,
    resolvedAt: row.resolved_at,
    isAutoGenerated: row.is_auto_generated,
  };
}

export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  try {
    const supabase = await createClient();

    const {
      data: { user },
    } = await supabase.auth.getUser();
    if (!user) {
      return new Response(JSON.stringify({ error: 'Unauthorized' }), { status: 401 });
    }

    const { data: userData } = await supabase
      .from('users')
      .select('role')
      .eq('id', user.id)
      .single();

    if (!userData || (userData.role !== 'admin' && userData.role !== 'super_admin')) {
      return new Response(JSON.stringify({ error: 'Forbidden' }), { status: 403 });
    }

    const body = await request.json();
    const { status, notes, due_date, priority, task_category, title } = body;

    const updateData: Record<string, unknown> = {};
    if (status !== undefined) {
      updateData.status = status;
      if (status === 'closed') {
        updateData.resolved_at = new Date().toISOString();
      }
    }
    if (notes !== undefined) updateData.notes = notes;
    if (due_date !== undefined) updateData.due_date = due_date;
    if (priority !== undefined) updateData.priority = priority;
    if (task_category !== undefined) updateData.task_category = task_category;
    if (title !== undefined) updateData.title = title;

    const result = await supabase
      .from('admin_tasks' as never)
      .update(updateData as never)
      .eq('id', id)
      .select()
      .single();

    const { data, error } = result as any;

    if (error) {
      return new Response(JSON.stringify({ error: error.message }), { status: 500 });
    }

    if (!data) {
      return new Response(JSON.stringify({ error: 'Task not found' }), { status: 404 });
    }

    if (status) {
      await logActivity(user.id, `updated_admin_task_status_to_${status}`, 'admin_task', data.id, {
        taskId: data.id,
        newStatus: status,
      });
    }

    return new Response(JSON.stringify({ task: rowToTask(data) }), { status: 200 });
  } catch (err) {
    console.error('[PATCH /api/admin/tasks/[id]]', err);
    return new Response(JSON.stringify({ error: 'Internal server error' }), { status: 500 });
  }
}
